name: ${project.name}
main: com.poixson.backroomslite.BackroomsLitePlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
dependencies:
    server:
        VitalCore:
            load: BEFORE
            required: true
        Multiverse-Core:
            load: BEFORE
            required: true
authors: lorenzop
website: ${project.url}
description: ${project.description}
